apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: default
spec:
  restartPolicy: OnFailure

  containers:
  - name: busywriter
    image: busybox:1.28
    command:
      - sh
      - -c
      - |
        while true; do
          echo "Hello, Kubernetes! $(date)" >> /data/out.txt
          sleep 5
        done
    volumeMounts:
      - name: file-share
        mountPath: /data

  - name: busyreader
    image: busybox:1.28
    command:
      - sh
      - -c
      - |
        while true; do
          tail -f /read/out.txt || true
          sleep 5
        done
    volumeMounts:
      - name: file-share
        mountPath: /read

  volumes:
  - name: file-share
    emptyDir:
      sizeLimit: 500Mi
      medium: Memory